mcqMaster/ViewModels/SortButton.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mcqMaster.ViewModels
{
    /// <summary>
    /// The ViewModel for the Sort Button partial view used to sort the tables in the app
    /// </summary>
    public class SortButton
    {
        public string Action { get; set; }
        public string Controller { get; set; }

        public string SortBy { get; set; }
        public bool IsAlphabetic { get; set; }
        public bool IsDefault { get; set; }
        public bool IsDefaultDescending { get; set; }
    }
}

mcqMaster/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mcqMaster.DAL;
using mcqMaster.Models;
using mcqMaster.ViewModels;
using Microsoft.AspNet.Identity;
using PagedList;

namespace mcqMaster.Controllers
{
    /// <summary>
    /// Controller for Test functionality
    /// </summary>
    [Authorize]
    public class TestController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private static readonly int PageSize = 20;

        /// <summary>
        /// Displays an index of Public Tests
        /// </summary>
        /// <param name="searchTerm">Search string to filter by</param>
        /// <param name="sortBy">Column to sort on</param>
        /// <param name="sortMode">Ascending or Descending</param>
        /// <param name="page">Current Page</param>
        /// <returns>The View for the Public Tests index</returns>
        [AllowAnonymous]
        public ActionResult Index(string searchTerm, string sortBy, string sortMode, int page = 1)
        {
            var tests = db.Tests.Where(t => t.IsPublic).ToList();

            var testIndex = prepareTestIndex(tests, searchTerm, sortBy, sortMode, page);

            return View(testIndex);
        }

        /// <summary>
        /// Displays the index for My Tests page
        /// </summary>
        /// <param name="searchTerm">Search string to filter by</param>
        /// <param name="sortBy">Column to sort on</param>
        /// <param name="sortMode">Ascending or Descending</param>
        /// <param name="page">Current Page</param>
        /// <returns>The View for My Tests</returns>
        public ActionResult MyTests(string searchTerm, string sortBy, string sortMode, int page = 1)
        {
            var currentUser = User.Identity.GetUserId();
            var tests = db.Tests.Where(q => q.AspNetUserId == currentUser).ToList();

            var testIndex = prepareTestIndex(tests, searchTerm, sortBy, sortMode, page);

            return View(testIndex);
        }

        /// <summary>
        /// Displays the test details view for the given test
        /// </summary>
        /// <param name="id">Test ID</param>
        /// <param name="searchTerm">Search string to filter by</param>
        /// <param name="sortBy">Column to sort on</param>
        /// <param name="sortMode">Ascending or Descending</param>
        /// <param name="page">Current Page</param>
        /// <returns>The Details view for the specified test</returns>
        [AllowAnonymous]
        public ActionResult Details(int? id, string searchTerm, string sortBy, string sortMode, int page = 1)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }

            var selectedQuestions = test.TestQuestions.Select(tq => tq.QuestionId).ToList();
            var testDetailsViewModel = new TestDetailsViewModel
            {
                Test = test
            };
            testDetailsViewModel.Questions = prepareQuestionIndex(db.Questions.Where(q => selectedQuestions.Contains(q.Id)).OrderBy(q => q.Id), searchTerm, sortBy, sortMode, page).ToPagedList(page, PageSize);

            return View(testDetailsViewModel);
        }

        /// <summary>
        /// Sets up Test Creation and redirects the user to Select Questions
        /// </summary>
        /// <returns>Redirect to Select Questions</returns>
        public ActionResult Create()
        {
            Session["SelectedQuestions"] = new List<int>();
            return RedirectToAction("SelectQuestions");
        }

        /// <summary>
        /// Sets up Test Editing and redirects the user to Test Finalization
        /// </summary>
        /// <param name="id">Test ID to edit</param>
        /// <returns>Redirect to Test Finalize</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            Session["SelectedQuestions"] = test.TestQuestions.Select(tq => tq.QuestionId).ToList();
            return RedirectToAction("Finalize", new { id });
        }

        /// <summary>
        /// Returns the view that allows the user to select questions for the test (edit or create)
        /// </summary>
        /// <param name="id">Test ID</param>
        /// <param name="searchTerm">Search string to filter by</param>
        /// <param name="sortBy">Column to sort questions on</param>
        /// <param name="sortMode">Ascending or Descending</param>
        /// <param name="page">Current page</param>
        /// <returns>The view for Question selection</returns>
        public ActionResult SelectQuestions(int? id, string searchTerm, string sortBy, string sortMode, int page = 1)
        {
            ViewBag.EditMode = id == null ? false : true;
            var currentUser = User.Identity.GetUserId();
            var questions = db.Questions.Where(q => q.AspNetUserId == currentUser || q.IsPublic).Include(q => q.Subject);

            var questionIndex = prepareQuestionIndex(questions, searchTerm, sortBy, sortMode, page);

            //Convert to SelectQuestionViewModel list
            if (Session["SelectedQuestions"] == null)
            {
                Session["SelectedQuestions"] = new List<int>();
            }

            var selectedQuestions = (List<int>)Session["SelectedQuestions"];
            var selectableQuestions = new List<SelectQuestionViewModel>();
            foreach (Question question in questionIndex)
            {
                var selectableQuestion = new SelectQuestionViewModel();
                selectableQuestion.Question = question;

                if (selectedQuestions.Contains(question.Id))
                {
                    selectableQuestion.IsSelected = true;
                }

                selectableQuestions.Add(selectableQuestion);
            }
            var selectableQuestionIndex = selectableQuestions.ToPagedList(page, PageSize);

            ViewBag.Page = page;
            ViewBag.SelectedQuestions = selectedQuestions.Count;

            return View(selectableQuestionIndex);
        }

        /// <summary>
        /// Returns the view for Test Finalization during create/edit test
        /// </summary>
        /// <param name="id">Test ID</param>
        /// <param name="searchTerm">Search string to filter by</param>
        /// <param name="sortBy">Column to sort on</param>
        /// <param name="sortMode">Ascending or Descending</param>
        /// <param name="page">Current Page</param>
        /// <returns>A View for the Finalization form for test create/edit</returns>
        public ActionResult Finalize(int? id, string searchTerm, string sortBy, string sortMode, int page = 1)
        {
            ViewBag.EditMode = id == null ? false : true;
            var selectedQuestions = (List<int>)Session["SelectedQuestions"];
            if (selectedQuestions == null)
            {
                return RedirectToAction("MyTests");
            }
            if (selectedQuestions.Count <= 0)
            {
                return RedirectToAction("MyTests");
            }

            FinalizeTestViewModel model;
            if (id == null)
            {
                model = new FinalizeTestViewModel();
                model.PresentAll = true;
            }
            else
            {
                Test test = db.Tests.Find(id);
                if (test == null)
                {
                    return HttpNotFound();
                }
                if (test.AspNetUserId != User.Identity.GetUserId())
                {
                    return RedirectToAction("Index");
                }
                model = new FinalizeTestViewModel
                {
                    TestName = test.TestName,
                    IsPublic = test.IsPublic,
                    PresentAll = test.PresentAll
                };
            }
            
            var questions = db.Questions.Where(q => selectedQuestions.Contains(q.Id));

            model.Questions = prepareQuestionIndex(questions, searchTerm, sortBy, sortMode, page).ToPagedList(page, PageSize);

            ViewBag.Page = page;

            return View(model);
        }

        /// <summary>
        /// Handles POST submission of the Finalize Test form
        /// </summary>
        /// <param name="id">Test ID</param>
        /// <param name="model">ViewModel containing form values</param>
        /// <returns>Redirects to My Test on success</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Finalize(int? id, FinalizeTestViewModel model)
        {
            if (ModelState.IsValid)
            {
                var selectedQuestions = (List<int>)Session["SelectedQuestions"];
                if (id == null)
                {
                    var test = new Test
                    {
                        TestName = model.TestName,
                        PresentAll = model.PresentAll,
                        IsPublic = model.IsPublic
                    };
                    db.Tests.Add(test);

                    foreach (int questionId in selectedQuestions)
                    {
                        var testQuestion = new TestQuestion
                        {
                            TestId = test.Id,
                            QuestionId = questionId
                        };
                        db.TestQuestions.Add(testQuestion);

mcqMaster/Views/Shared/SortButton.cshtml
@model mcqMaster.ViewModels.SortButton
@{
    bool isSortedByThisColumn;
    if (Model.IsDefault)
    {
        isSortedByThisColumn = ViewBag.SortBy == null;
    }
    else
    {
        isSortedByThisColumn = ViewBag.SortBy != null && ViewBag.SortBy.Equals(Model.SortBy);
    }

    if (isSortedByThisColumn)
    {
        if (ViewBag.SortMode != null &&
            ViewBag.SortMode.Equals("desc"))
        {
            <a class="btn btn-xs btn-default" href="@Url.Action(Model.Action, Model.Controller, new { @sortBy = Model.SortBy, @searchTerm = ViewBag.SearchTerm, @page = ViewBag.Page, @mode = ViewBag.SelectedMode })">
                @if (Model.IsAlphabetic)
                {
                    <span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>
                }
                else
                {
                    <span class="glyphicon glyphicon-sort-by-attributes-alt"></span>
                }
            </a>
        }
        else
        {
            <a class="btn btn-xs btn-default" href="@Url.Action(Model.Action, Model.Controller, new { @sortBy = Model.SortBy, @sortMode = "desc", @searchTerm = ViewBag.SearchTerm, @page = ViewBag.Page, @mode = ViewBag.SelectedMode })">
                @if (Model.IsAlphabetic)
                {
                    <span class="glyphicon glyphicon-sort-by-alphabet"></span>
                }
                else
                {
                    <span class="glyphicon glyphicon-sort-by-attributes"></span>
                }
            </a>
        }
    }
    else
    {
        if (Model.IsDefaultDescending)
        {
            <a class="btn btn-xs btn-default" href="@Url.Action(Model.Action, Model.Controller, new { @sortBy = Model.SortBy, @sortMode = "desc", @searchTerm = ViewBag.SearchTerm, @page = ViewBag.Page, @mode = ViewBag.SelectedMode })">
                <span class="glyphicon glyphicon-sort"></span>
            </a>
        }
        else
        {
            <a class="btn btn-xs btn-default" href="@Url.Action(Model.Action, Model.Controller, new { @sortBy = Model.SortBy, @searchTerm = ViewBag.SearchTerm, @page = ViewBag.Page, @mode = ViewBag.SelectedMode })">
                <span class="glyphicon glyphicon-sort"></span>
            </a>
        }
    }
}

mcqMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - mcqMaster</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("mcqMaster", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Public Questions", "Index", "Question")</li>
                    @if (HttpContext.Current.User.Identity.IsAuthenticated) {
                        <li>@Html.ActionLink("My Questions", "MyQuestions", "Question")</li>
                    }
                    <li>@Html.ActionLink("Public Tests", "Index", "Test")</li>
                    @if (HttpContext.Current.User.Identity.IsAuthenticated) {
                        <li>@Html.ActionLink("My Tests", "MyTests", "Test")</li>
                    }
                    @if(HttpContext.Current.User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("Admin", "UserIndex", "Account")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderSection("featured", required: false)
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Maurice de Vries</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>