mcqMaster/Models/Test.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace mcqMaster.Models
{
    public class Test
    {
        public int Id { get; set; }

        [StringLength(128)]
        public String AspNetUserId { get; set; }

        [Required]
        [Column(TypeName = "VARCHAR")]
        [StringLength(128)]
        [Index("TestNameIndex", IsUnique = true)]
        [Display(Name = "Test Name")]
        public String TestName { get; set; }

        public bool PresentAll { get; set; }
        public bool IsPublic { get; set; }

        [Required]
        public DateTime CreatedDate { get; set; }

        [Required]
        public DateTime UpdatedDate { get; set; }

        public virtual ApplicationUser AspNetUser { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
        public virtual ICollection<SharedTest> SharedTests { get; set; }
        public virtual ICollection<Attempt> Attempts { get; set; }

        public Test()
        {
            AspNetUserId = HttpContext.Current.User.Identity.GetUserId();
            CreatedDate = DateTime.Now;
            UpdatedDate = DateTime.Now;
        }
    }
}

mcqMaster/ViewModels/TestViewModels.cs
using mcqMaster.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mcqMaster.ViewModels
{
    /// <summary>
    /// The value fields for the Test Index Pages (Public and My Tests)
    /// </summary>
    public class TestIndexViewModel
    {
        public Test Test { get; set; }
        public List<string> Subjects { get; set; }
    }

    /// <summary>
    /// Form fields for the Select Questions part of the Create Test workflow
    /// </summary>
    public class SelectQuestionViewModel
    {
        public Question Question { get; set; }
        public bool IsSelected { get; set; }
    }

    /// <summary>
    /// Form fields for the Finalize Test part of the Create Test workflow
    /// </summary>
    public class FinalizeTestViewModel
    {
        public IPagedList<Question> Questions { get; set; }

        [Required]
        [Display(Name = "Test Name")]
        [StringLength(128, ErrorMessage = "Cannot be greater than 128 characters")]
        public String TestName { get; set; }

        [Display(Name = "Present All Questions?")]
        public bool PresentAll { get; set; }

        [Display(Name = "Make Public?")]
        public bool IsPublic { get; set; }
    }

    /// <summary>
    /// View values for the Test Details page
    /// </summary>
    public class TestDetailsViewModel
    {
        public IPagedList<Question> Questions { get; set; }
        public Test Test { get; set; }
    }

    /// <summary>
    /// View values for the Test Finished page
    /// </summary>
    public class TestFinishedViewModel
    {
        public Test Test { get; set; }
        public Attempt Attempt { get; set; }
        public int AnsweredQuestions { get; set; }
        public int CorrectResponses { get; set; }

        [DisplayFormat(DataFormatString = "{0:P1}", ApplyFormatInEditMode = true)]
        public double Score { get; set; }
    }

    /// <summary>
    /// ViewModel for the test rows on the User Statistics page
    /// </summary>
    public class UserTestStatisticsViewModel
    {
        public Test Test { get; set; }
        public List<string> Subjects { get; set; }
        public int CorrectResponses { get; set; }

        [Display(Name = "Date Taken")]
        public DateTime DateTaken { get; set; }

        [DisplayFormat(DataFormatString = "{0:P1}", ApplyFormatInEditMode = true)]
        public double Score { get; set; }
    }

    /// <summary>
    /// View values for the Test Statistics
    /// </summary>
    public class TestStatisticsViewModel
    {
        public Test Test { get; set; }

        public string Mode { get; set; }
        public IEnumerable<SelectListItem> Modes { get; set; }

        [Display(Name = "Average Score:")]
        [DisplayFormat(DataFormatString = "{0:P1}", ApplyFormatInEditMode = true)]
        public double AverageScore { get; set; }

        [Display(Name = "Times Taken:")]
        public int TimesTaken { get; set; }

        [Display(Name = "Unique Users:")]
        public int UniqueUsers { get; set; }

        public IPagedList<TestQuestionStatisticsViewModel> Questions { get; set; }
        public IPagedList<TestAttemptStatisticsViewModel> Attempts { get; set; }

        public TestStatisticsViewModel()
        {
            var options = new List<SelectListItem>();
            options.Add(new SelectListItem
            {
                Value = "overall",
                Text = "Overall"
            });
            options.Add(new SelectListItem
            {
                Value = "question",
                Text = "By Question"
            });
            options.Add(new SelectListItem
            {
                Value = "user",
                Text = "By User"
            });
            Modes = options;
        }
    }

    /// <summary>
    /// ViewModel for the rows in the table on Test Statistics - By Question
    /// </summary>
    public class TestQuestionStatisticsViewModel
    {
        public Question Question { get; set; }

        [DisplayFormat(DataFormatString = "{0:P1}", ApplyFormatInEditMode = true)]
        public double Score { get; set; }
    }

    /// <summary>
    /// ViewModel for the rows in Test Statistics - By User
    /// </summary>
    public class TestAttemptStatisticsViewModel
    {
        public Attempt Attempt { get; set; }

        public int CorrectResponses { get; set; }

        [DisplayFormat(DataFormatString = "{0:P1}", ApplyFormatInEditMode = true)]
        public double Score { get; set; }
    }
}

mcqMaster/Controllers/ProfileController.cs
using mcqMaster.DAL;
using mcqMaster.Models;
using mcqMaster.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace mcqMaster.Controllers
{
    /// <summary>
    /// Controller for Profile functionality
    /// </summary>
    [Authorize]
    public class ProfileController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private static readonly int PageSize = 20;

        /// <summary>
        /// Shows the default profile page for a user
        /// </summary>
        /// <param name="username">Which user to show the profile for, default is the current user</param>
        /// <returns>The View for the main profile page</returns>
        [AllowAnonymous]
        public ActionResult Index(string username)
        {
            ApplicationUser user;
            if (username == null)
            {
                user = db.Users.Find(User.Identity.GetUserId());
            }
            else
            {
                user = db.Users.Where(u => u.UserName == username).FirstOrDefault();
                if (user == null)
                {
                    return HttpNotFound();
                }
                if (!user.IsProfilePublic)
                {
                    return HttpNotFound();
                }
            }

            ViewBag.Age = calculateAge(user.DateOfBirth);

            return View(user);
        }

        /// <summary>
        /// Shows the edit page for the user's profile
        /// </summary>
        /// <returns>The View for the Edit Profile Page</returns>
        public ActionResult Edit()
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            var model = new EditProfileViewModel
            {
                AspNetUserId = user.Id,
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                GenderId = user.GenderId,
                Gender = user.Gender,
                PhotoPath = user.PhotoPath,
                IsDobPublic = user.IsDobPublic,
                FavouriteSubjects = user.FavouriteSubjects,
                About = user.About
            };

            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Description", user.GenderId);

            return View(model);
        }

        /// <summary>
        /// Handles POST submission of the Edit Profile form
        /// </summary>
        /// <param name="model">The ViewModel of the Edit page containing the form data</param>
        /// <returns>Redirects the user to the main profile page on success</returns>
        [HttpPost]
        public ActionResult Edit(EditProfileViewModel model)
        {
            var user = db.Users.Find(model.AspNetUserId);
            if (ModelState.IsValid)
            {               

                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.PhotoPath = model.PhotoPath;
                user.GenderId = model.GenderId;
                user.Gender = model.Gender;
                user.IsDobPublic = model.IsDobPublic;
                user.FavouriteSubjects = model.FavouriteSubjects;
                user.About = model.About;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Description", user.GenderId);
            return View(model);
        }

        /// <summary>
        /// Displays the Account Settings profile page
        /// </summary>
        /// <returns>The View for the Account Settings page</returns>
        public ActionResult AccountSettings()
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            var model = new AccountSettingsViewModel
            {
                AspNetUserId = user.Id,
                UserName = user.UserName,
                PhotoPath = user.PhotoPath,
                IsProfilePublic = user.IsProfilePublic,
                IsNewQuestionPublic = user.IsNewQuestionPublic
            };

            return View(model);
        }

        /// <summary>
        /// Handles POST submission of the Account Settings page
        /// </summary>
        /// <param name="model">The ViewModel for the account settings containing the form values</param>
        /// <returns>Redirects to the main profile page on success</returns>
        [HttpPost]
        public ActionResult AccountSettings(AccountSettingsViewModel model)
        {
            var user = db.Users.Find(model.AspNetUserId);
            if (ModelState.IsValid)
            {

                user.IsProfilePublic = model.IsProfilePublic;
                user.IsNewQuestionPublic = model.IsNewQuestionPublic;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// Populates the User Statistics page of the profile with the user's data, filtered using the parameters
        /// </summary>
        /// <param name="mode">The mode that the stats page is in i.e., overall/by subject/by test</param>
        /// <param name="subject">The currently selected subject to filter by</param>
        /// <param name="testId">The testId to filter by</param>
        /// <param name="searchTerm">The search string to filter by</param>
        /// <param name="sortBy">Which column to sort the results on</param>
        /// <param name="sortMode">Whether to sort ascending or descending</param>
        /// <param name="page">The current page number</param>
        /// <returns>A View of the user's statistics</returns>
        public ActionResult Statistics(string mode, int? subject, int? testId, string searchTerm, string sortBy, string sortMode, int page = 1)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            List<Attempt> attempts = db.Attempts.Where(attempt => attempt.AspNetUserId.Equals(user.Id)).ToList();
            var responses = db.Responses.Where(response => response.Attempt.AspNetUserId.Equals(user.Id)).ToList();

            var model = new UserStatisticsViewModel
            {
                AspNetUserId = user.Id,
                UserName = user.UserName,
                PhotoPath = user.PhotoPath,
                Tests = new List<UserTestStatisticsViewModel>().ToPagedList(1, PageSize)
            };

            if (mode != null && mode.Equals("subject") && subject != null)
            {
                responses = responses.Where(response => response.Option.Question.Subject.Id == subject).ToList();

                var attemptIds = new List<int>();
                foreach (Response response in responses)
                {
                    attemptIds.Add(response.Attempt.Id);
                }

                attempts = attempts.Where(attempt => attemptIds.Contains(attempt.Id)).ToList();
            }
            else if(mode != null && mode.Equals("test"))
            {
                if (testId != null)
                {
                    attempts = attempts.Where(attempt => attempt.TestId == testId).ToList();
                }

                var attemptIds = new List<int>();
                foreach(Attempt attempt in attempts)
                {
                    attemptIds.Add(attempt.Id);
                }

                responses = responses.Where(response => attemptIds.Contains(response.Attempt.Id)).ToList();

                model.Tests = prepareTestIndex(attempts, searchTerm, sortBy, sortMode, page);
            }

            model.TestsTaken = attempts.Count;
            model.UniqueTests = attempts.GroupBy(attempt => attempt.Test.Id).Select(g => g.First()).ToList().Count;

            var correctResponses = 0;
            foreach (Response response in responses)
            {
                if (response.Option.IsCorrect)
                {
                    correctResponses++;
                }
            }
            model.AverageScore = (double)correctResponses / responses.Count;

            ViewBag.SelectedMode = mode;

            ViewBag.Mode = new SelectList(model.Modes, "Value", "Text", mode);

            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Description", subject);           

            return View(model);
        }

        /// <summary>
        /// Method to calculate age from DoB
        /// </summary>
        /// <param name="dob">Date of Birth</param>
        /// <returns>The current age of the person based on DoB</returns>
        private int calculateAge(DateTime dob)
        {
            var age = DateTime.Today.Year - dob.Year;
            if (DateTime.Today < dob.AddYears(age))
            {
                age--;
            }
            return age;
        }

        /// <summary>
        /// Prepares an IPagedList of test attempts to populate the table in the User Statistics page
        /// </summary>
        /// <param name="attempts">An unorganized list of the test attempts made</param>
        /// <param name="searchTerm">Search string to filter by</param>
        /// <param name="sortBy">Column to sort on</param>
        /// <param name="sortMode">Ascending or descending</param>
        /// <param name="page">The current page number</param>
        /// <returns></returns>
        private IPagedList<UserTestStatisticsViewModel> prepareTestIndex(List<Attempt> attempts, string searchTerm, string sortBy, string sortMode, int page)
        {
            //Convert to TestStatisticsViewModel
            var testStatisticsViewModels = new List<UserTestStatisticsViewModel>();
            for (int i = 0; i < attempts.Count; i++)
            {

                var testStatisticsViewModel = new UserTestStatisticsViewModel();
                testStatisticsViewModel.Test = attempts[i].Test;

mcqMaster/Views/Test/Delete.cshtml
@model mcqMaster.Models.Test

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Test</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PresentAll)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PresentAll)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a href="javascript:history.back()" class="btn btn-default">Back</a>
        </div>
    }
</div>

mcqMaster/Views/Test/Index.cshtml
@model PagedList.IPagedList<mcqMaster.ViewModels.TestIndexViewModel>
@using PagedList.Mvc;
@using mcqMaster.ViewModels;
@{
    ViewBag.Title = "Public Tests";
}

<h2>Public Tests</h2>

<div class="row">
    <div class="col-xs-12 col-md-3">
        <form method="get">
            <div class="input-group">
                <input type="text" name="searchTerm" class="form-control col-xs-12" placeholder="Search for...">
                @if (ViewBag.SortBy != null)
                {
                    <input type="hidden" name="sortBy" value="@ViewBag.SortBy" />
                }
                @if (ViewBag.SortMode != null)
                {
                    <input type="hidden" name="sortMode" value="@ViewBag.SortMode" />
                }
                <input type="hidden" name="page" value="1" />
                <span class="input-group-btn">
                    <input class="btn btn-default" type="submit" value="Search" />
                </span>
            </div>
        </form>
    </div>
    <div class="text-center col-xs-12 col-md-6">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortBy = ViewBag.SortBy, sortMode = ViewBag.SortMode, searchTerm = ViewBag.SearchTerm }))
    </div>
</div>

<table class="table">
    <colgroup>
        <col width="15%" />
        <col width="15%"/>
        <col width="15%" />
        <col />
        <col />
        <col />
    </colgroup>
    <tr>
        <th scope="col">
            @Html.DisplayNameFor(model => model.FirstOrDefault().Test.TestName)
            @Html.Partial("SortButton", new SortButton { IsDefault = true, IsAlphabetic = true, Action = "Index", Controller = "Test" })
        </th>
        <th scope="col">
            Subject(s)
            @Html.Partial("SortButton", new SortButton { SortBy = "subject", IsAlphabetic = true, Action = "Index", Controller = "Test" })
        </th>
        <th scope="col">
            Creator
            @Html.Partial("SortButton", new SortButton { SortBy = "creator", IsAlphabetic = true, Action = "Index", Controller = "Test" })
        </th>
        <th scope="col">
            # of Questions
            @Html.Partial("SortButton", new SortButton { SortBy = "questions", IsDefaultDescending = true, Action = "Index", Controller = "Test" })
        </th>
        <!--<th scope="col">
            Difficulty
            Html.Partial("SortButton", new SortButton { SortBy = "difficulty", IsDefaultDescending = true, Action = "Index", Controller = "Test" })
        </th>-->
        <th scope="col">
            @Html.DisplayNameFor(model => model.FirstOrDefault().Test.UpdatedDate)
            @Html.Partial("SortButton", new SortButton { SortBy = "updated", IsDefaultDescending = true, Action = "Index", Controller = "Test" })
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th scope="row">
                @Html.ActionLink(@Html.DisplayFor(modelItem => item.Test.TestName).ToString(), "Details", new { id = item.Test.Id })
            </th>
            <td>
                @{
                    string subjects = "";
                    if (item.Subjects.Count > 3)
                    {
                        subjects = "Various";
                    }
                    else
                    {
                        for (int i = 0; i < item.Subjects.Count; i++)
                        {
                            subjects += item.Subjects[i];
                            if (i != item.Subjects.Count - 1)
                            {
                                subjects += ", ";
                            }
                        }
                    }
                }
                @subjects
            </td>
            <td>
                <a href="@Url.Action("Index", "Profile", new { username = item.Test.AspNetUser.UserName })">@Html.DisplayFor(modelItem => item.Test.AspNetUser.UserName)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Test.TestQuestions.Count)
            </td>
            <!--<td>
                <!--Difficulty
            </td>-->
            <td>
                @Html.DisplayFor(modelItem => item.Test.UpdatedDate)
            </td>
            <td>
                @Html.ActionLink("Take Test", "TakeTest", new { id = item.Test.Id }, new { @class = "btn btn-primary" })
            </td>
        </tr>
    }

</table>

mcqMaster/Views/Test/MyTests.cshtml
@model PagedList.IPagedList<mcqMaster.ViewModels.TestIndexViewModel>
@using PagedList.Mvc;
@using mcqMaster.ViewModels;
@{
    ViewBag.Title = "My Tests";
}

<h2>My Tests</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>

<div class="row">
    <div class="col-xs-12 col-md-3">
        <form method="get">
            <div class="input-group">
                <input type="text" name="searchTerm" class="form-control col-xs-12" placeholder="Search for...">
                @if (ViewBag.SortBy != null)
                {
                    <input type="hidden" name="sortBy" value="@ViewBag.SortBy" />
                }
                @if (ViewBag.SortMode != null)
                {
                    <input type="hidden" name="sortMode" value="@ViewBag.SortMode" />
                }
                <input type="hidden" name="page" value="1" />
                <span class="input-group-btn">
                    <input class="btn btn-default" type="submit" value="Search" />
                </span>
            </div>
        </form>
    </div>
    <div class="text-center col-xs-12 col-md-6">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortBy = ViewBag.SortBy, sortMode = ViewBag.SortMode, searchTerm = ViewBag.SearchTerm }))
    </div>
</div>

<table class="table">
    <colgroup>
        <col width="15%"/>
        <col width="15%"/>
        <col width="15%" />
        <col />
        <col />
        <col />
        <col />
    </colgroup>
    <tr>
        <th scope="col">
            @Html.DisplayNameFor(model => model.FirstOrDefault().Test.TestName)
            @Html.Partial("SortButton", new SortButton { IsDefault = true, IsAlphabetic = true, Action = "Index", Controller = "Test" })
        </th>
        <th scope="col">
            Subject(s)
            @Html.Partial("SortButton", new SortButton { SortBy = "subject", IsAlphabetic = true, Action = "Index", Controller = "Test" })
        </th>
        <th scope="col">
            Creator
            @Html.Partial("SortButton", new SortButton { SortBy = "creator", IsAlphabetic = true, Action = "Index", Controller = "Test" })
        </th>
        <th scope="col">
            # of Questions
            @Html.Partial("SortButton", new SortButton { SortBy = "questions", IsDefaultDescending = true, Action = "Index", Controller = "Test" })
        </th>
        <!--<th scope="col">
            Difficulty
            Html.Partial("SortButton", new SortButton { SortBy = "difficulty", IsDefaultDescending = true, Action = "Index", Controller = "Test" })
        </th>-->
        <th scope="col">
            @Html.DisplayNameFor(model => model.FirstOrDefault().Test.UpdatedDate)
            @Html.Partial("SortButton", new SortButton { SortBy = "updated", IsDefaultDescending = true, Action = "Index", Controller = "Test" })
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th scope="row">
                @Html.ActionLink(@Html.DisplayFor(modelItem => item.Test.TestName).ToString(), "Details", new { id = item.Test.Id })
            </th>
            <td>
                @{
                    string subjects = "";
                    if (item.Subjects.Count > 3)
                    {
                        subjects = "Various";
                    }
                    else
                    {
                        for (int i = 0; i < item.Subjects.Count; i++)
                        {
                            subjects += item.Subjects[i];
                            if (i != item.Subjects.Count - 1)
                            {
                                subjects += ", ";
                            }
                        }
                    }
                }
                @subjects
            </td>
            <td>
                <a href="@Url.Action("Index", "Profile", new { username = item.Test.AspNetUser.UserName })">@Html.DisplayFor(modelItem => item.Test.AspNetUser.UserName)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Test.TestQuestions.Count)
            </td>
            <!--<td>
                <!--Difficulty
            </td>-->
            <td>
                @Html.DisplayFor(modelItem => item.Test.UpdatedDate)
            </td>
            <td>
                @Html.ActionLink("Take Test", "TakeTest", new { id = item.Test.Id }, new { @class = "btn btn-primary" })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Test.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Test.Id })
            </td>
        </tr>
    }

</table>

mcqMaster/Views/Test/TakeTest.cshtml
@model mcqMaster.Models.Test
@{
    ViewBag.Title = "TakeTest";
}

<h2>Take Test: @Html.DisplayFor(model => model.TestName)</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-default form-horizontal">
        <div class="panel-heading">
            <h3 class="h4">Test Details</h3>
        </div>
        <div class="panel-body">
            <div class="row mcq-vertical-align mcq-my-2">
                <div class="col-xs-2">
                    <strong>Creator</strong>
                </div>
                <div class="col-xs-10 col-md-6">
                    @Html.DisplayFor(model => model.AspNetUser.UserName)
                </div>
            </div>
            <div class="row mcq-vertical-align mcq-my-2">
                <div class="col-xs-2">
                    <strong>Number of Questions</strong>
                </div>
                <div class="col-xs-10 col-md-6">
                    @Html.DisplayFor(model => model.TestQuestions.Count)
                </div>
            </div>

            <!--if (!Model.PresentAll)
    {
        -->
            <div class="row mcq-vertical-align mcq-my-2">
                <div class="col-xs-2">
                    <strong>@Html.DisplayNameFor(model => model.PresentAll)</strong>
                </div>
                <div class="col-xs-10 col-md-6">
                    @Html.EditorFor(model => model.PresentAll)
                </div>
            </div>
            <!--}-->


        </div>
        <div class="panel-footer">
            <div>
                <button type="submit" class="btn btn-primary">Start Test</button>
                <a href="javascript:history.back()" class="btn btn-default">Back</a>
            </div>
        </div>
    </div>
}

mcqMaster/Views/Test/TestFinished.cshtml
@model mcqMaster.ViewModels.TestFinishedViewModel
@{
    ViewBag.Title = "Test Complete";
}

<h2>Test Complete</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@Model.Test.TestName Complete</h3>
    </div>
    <div class="panel-body">
        <p class="h4">
            You scored <strong>@Html.DisplayFor(mcqMaster => mcqMaster.Score)</strong>
        </p>
        <p class="h4">
            You answered @Model.CorrectResponses questions correctly out of @Model.AnsweredQuestions.
        </p>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Return to Index", "Index", null, new { @class = "btn btn-primary" })
    </div>
</div>